name: frledger
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  carbon_icons: ^0.0.1
  sprintf: "^5.0.0"
  package_info_plus: ^1.0.6
  sqflite:
  path:
  restart_app: ^1.1.0
  fluttertoast: ^8.0.9
  flutter_styled_toast: ^2.1.3
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/langs/
  
  fonts:
    - family: Noto Sans TC
      fonts:
        - asset: assets/fonts/notosanstc/NotoSansTC-Regular.otf
        - asset: assets/fonts/notosanstc/NotoSansTC-Thin.otf
          weight: 100
        - asset: assets/fonts/notosanstc/NotoSansTC-Light.otf
          weight: 300
        - asset: assets/fonts/notosanstc/NotoSansTC-Medium.otf
          weight: 500
        - asset: assets/fonts/notosanstc/NotoSansTC-Bold.otf
          weight: 700
        - asset: assets/fonts/notosanstc/NotoSansTC-Black.otf
          weight: 900

    - family: Noto Sans
      fonts:
        - asset: assets/fonts/notosans/NotoSans-Regular.ttf
        - asset: assets/fonts/notosans/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/notosans/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/notosans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/notosans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/notosans/NotoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/notosans/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/notosans/NotoSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/notosans/NotoSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/notosans/NotoSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/notosans/NotoSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/notosans/NotoSans-BlackItalic.ttf
          style: italic
          weight: 900


    - family: Victor Mono
      fonts:
        - asset: assets/fonts/victormono/VictorMono-Regular.otf
        - asset: assets/fonts/victormono/VictorMono-ExtraLight.otf
          weight: 100
        - asset: assets/fonts/victormono/VictorMono-ExtraLightItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/victormono/VictorMono-Light.otf
          weight: 300
        - asset: assets/fonts/victormono/VictorMono-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/victormono/VictorMono-SemiBold.otf
          weight: 500
        - asset: assets/fonts/victormono/VictorMono-SemiBoldItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/victormono/VictorMono-Bold.otf
          weight: 700
        - asset: assets/fonts/victormono/VictorMono-BoldItalic.otf
          weight: 700
          style: italic

  # see https://flutter.dev/custom-fonts/#from-packages

# Icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"